
name: Java CI with Maven

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "40 12 * * *" 
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: target/*.war
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

          
  deploy_prod:
    if: github.ref == 'refs/heads/master' 
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Deployment
       run: |
            ls -ltr; pwd
  deploy_dev:
    if: github.ref == 'refs/heads/master' 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deployment
      run: |
            ls -ltr; pwd
